#!/usr/bin/env bash
# =============================================================================
# Raspberry Pi — WireGuard VPN Client Setup (Mode A)
#
# Phone-Bridge VPN Router architecture:
#   Client -> Phone AP -> Pi (wlan0) -> wg0 -> VPN Server -> Internet
#
# What this does:
#   1. Installs WireGuard + iptables-persistent
#   2. (Optional) Connects wlan0 to the phone hotspot via NetworkManager
#   3. Installs iptables kill switch (default OUTPUT DROP except VPN)
#   4. Brings up wg0 using /etc/wireguard/wg0.conf (from the server setup)
#   5. Enables wg-quick@wg0 and rule persistence on boot
#
# Prerequisites:
#   1. Pi has /etc/wireguard/wg0.conf in place (generated by setup-wireguard-server.sh)
#   2. Pi is already reachable (you're SSH'd in), typically via the phone hotspot
#
# Usage:
#   sudo bash setup-secure-router.sh
#   sudo bash setup-secure-router.sh --uplink-ssid "MyPhone" --uplink-pass "secret123"
# =============================================================================
set -euo pipefail

IF_UPLINK="wlan0"
WG_IFACE="wg0"
WG_CONF="/etc/wireguard/${WG_IFACE}.conf"

UPLINK_SSID=""
UPLINK_PASS=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --uplink-ssid) UPLINK_SSID="$2"; shift 2 ;;
        --uplink-pass) UPLINK_PASS="$2"; shift 2 ;;
        -h|--help)
            grep -E "^#" "$0" | sed 's/^# \?//'
            exit 0 ;;
        *) echo "Unknown argument: $1"; exit 1 ;;
    esac
done

log()  { echo "[*] $1"; }
ok()   { echo "     [OK] $1"; }
warn() { echo "     [WARN] $1"; }
err()  { echo "[ERROR] $1"; exit 1; }
step() { echo ""; echo "===> $1"; }

[[ $EUID -eq 0 ]] || err "Run as root (sudo)."

# -----------------------------------------------------------------------------
# 1. VERIFY WIREGUARD CONFIG
# -----------------------------------------------------------------------------
step "Verifying $WG_CONF"
[[ -f "$WG_CONF" ]] || err "$WG_CONF not found.
    Run setup-wireguard-server.sh on the VPS first,
    then copy pi-client.conf to $WG_CONF on this Pi."
chmod 600 "$WG_CONF"

VPN_ENDPOINT=$(grep -E "^[[:space:]]*Endpoint" "$WG_CONF" | awk -F'=' '{print $2}' | tr -d ' ')
VPN_ENDPOINT_HOST="${VPN_ENDPOINT%:*}"
VPN_ENDPOINT_PORT="${VPN_ENDPOINT#*:}"
[[ -n "$VPN_ENDPOINT_HOST" && -n "$VPN_ENDPOINT_PORT" ]] \
    || err "Could not parse Endpoint line from $WG_CONF"
ok "VPN endpoint: $VPN_ENDPOINT_HOST:$VPN_ENDPOINT_PORT"

# If the endpoint is a hostname, resolve it now (kill switch can't do DNS later)
if [[ ! "$VPN_ENDPOINT_HOST" =~ ^[0-9.]+$ ]]; then
    log "Resolving $VPN_ENDPOINT_HOST to IP (for kill switch rule)"
    RESOLVED=$(getent hosts "$VPN_ENDPOINT_HOST" | awk '{print $1; exit}')
    [[ -n "$RESOLVED" ]] || err "Could not resolve $VPN_ENDPOINT_HOST — use an IP in wg0.conf"
    VPN_ENDPOINT_HOST="$RESOLVED"
    ok "Resolved to $VPN_ENDPOINT_HOST"
fi

# -----------------------------------------------------------------------------
# 2. INSTALL PACKAGES
# -----------------------------------------------------------------------------
step "Installing packages"
export DEBIAN_FRONTEND=noninteractive
# Pre-seed iptables-persistent to avoid interactive prompt
echo "iptables-persistent iptables-persistent/autosave_v4 boolean true" | debconf-set-selections
echo "iptables-persistent iptables-persistent/autosave_v6 boolean true" | debconf-set-selections
apt-get update -qq
apt-get install -y -qq wireguard iptables-persistent resolvconf > /dev/null
ok "wireguard, iptables-persistent, resolvconf installed"

# -----------------------------------------------------------------------------
# 3. CONNECT TO PHONE HOTSPOT (if credentials provided)
# -----------------------------------------------------------------------------
step "Configuring uplink ($IF_UPLINK)"
if [[ -n "$UPLINK_SSID" ]]; then
    log "Connecting $IF_UPLINK to '$UPLINK_SSID'"
    nmcli connection delete "phone-uplink" 2>/dev/null || true
    nmcli connection add \
        type wifi \
        con-name "phone-uplink" \
        ifname "$IF_UPLINK" \
        ssid "$UPLINK_SSID" \
        wifi-sec.key-mgmt wpa-psk \
        wifi-sec.psk "$UPLINK_PASS" \
        connection.autoconnect yes
    nmcli connection up "phone-uplink" || warn "Could not activate now — will try on reboot"
    ok "Uplink configured: $UPLINK_SSID"
else
    log "No --uplink-ssid given — using current $IF_UPLINK connection"
    CUR=$(nmcli -t -f NAME,DEVICE connection show --active | awk -F: -v dev="$IF_UPLINK" '$2==dev{print $1}')
    [[ -n "$CUR" ]] && ok "Current connection on $IF_UPLINK: $CUR" || warn "$IF_UPLINK has no active connection"
fi

# -----------------------------------------------------------------------------
# 4. IP FORWARDING (future-proof for downstream clients)
# -----------------------------------------------------------------------------
step "Enabling IP forwarding"
cat > /etc/sysctl.d/99-vpn-router.conf << EOF
net.ipv4.ip_forward=1
EOF
sysctl -p /etc/sysctl.d/99-vpn-router.conf > /dev/null
ok "IP forwarding enabled"

# -----------------------------------------------------------------------------
# 5. KILL SWITCH — iptables rules
# Default OUTPUT DROP. Only allow:
#   - loopback
#   - established/related (SSH responses, etc.)
#   - DHCP on uplink
#   - UDP to VPN endpoint on uplink
#   - anything over wg0
# -----------------------------------------------------------------------------
step "Installing kill switch (iptables)"
iptables -F
iptables -t nat -F
iptables -X 2>/dev/null || true

iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

# --- INPUT ---
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -p icmp -j ACCEPT
iptables -A INPUT -i "$IF_UPLINK" -p tcp --dport 22 -j ACCEPT     # SSH from local LAN
iptables -A INPUT -i "$WG_IFACE" -j ACCEPT

# --- OUTPUT (kill switch) ---
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
# DHCP
iptables -A OUTPUT -o "$IF_UPLINK" -p udp --sport 68 --dport 67 -j ACCEPT
# ARP (not strictly needed — iptables doesn't filter ARP — but keep for clarity)
# VPN handshake/data to endpoint
iptables -A OUTPUT -o "$IF_UPLINK" -d "$VPN_ENDPOINT_HOST" -p udp --dport "$VPN_ENDPOINT_PORT" -j ACCEPT
# All tunneled traffic
iptables -A OUTPUT -o "$WG_IFACE" -j ACCEPT

# --- FORWARD (for downstream clients — enabled but sources restricted to wg0) ---
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -o "$WG_IFACE" -j ACCEPT

# NAT for any downstream traffic routed through wg0
iptables -t nat -A POSTROUTING -o "$WG_IFACE" -j MASQUERADE

mkdir -p /etc/iptables
iptables-save > /etc/iptables/rules.v4
ok "Kill switch active: only VPN traffic + handshake to $VPN_ENDPOINT_HOST:$VPN_ENDPOINT_PORT allowed out"

# -----------------------------------------------------------------------------
# 6. ENABLE WIREGUARD
# -----------------------------------------------------------------------------
step "Starting WireGuard tunnel"
systemctl enable "wg-quick@${WG_IFACE}" > /dev/null 2>&1
systemctl restart "wg-quick@${WG_IFACE}" || err "wg-quick@${WG_IFACE} failed — check: journalctl -u wg-quick@${WG_IFACE}"
sleep 2

if ip link show "$WG_IFACE" &>/dev/null; then
    ok "$WG_IFACE is up"
    HANDSHAKE=$(wg show "$WG_IFACE" latest-handshakes 2>/dev/null | awk '{print $2}')
    if [[ -n "$HANDSHAKE" && "$HANDSHAKE" != "0" ]]; then
        ok "Handshake confirmed"
    else
        warn "No handshake yet — check that the VPS is reachable and UDP ${VPN_ENDPOINT_PORT} is open in Oracle Cloud"
    fi
else
    err "$WG_IFACE did not come up"
fi

systemctl enable netfilter-persistent > /dev/null 2>&1 || true

# -----------------------------------------------------------------------------
# 7. SUMMARY
# -----------------------------------------------------------------------------
echo ""
echo "============================================="
echo "  PI VPN CLIENT SETUP COMPLETE"
echo "============================================="
echo ""
echo "  Uplink:       $IF_UPLINK -> phone hotspot"
echo "  VPN tunnel:   $WG_IFACE -> $VPN_ENDPOINT_HOST:$VPN_ENDPOINT_PORT"
echo "  Kill switch:  ACTIVE (default OUTPUT DROP)"
echo ""
echo "  Verify:"
echo "    sudo wg show                     # tunnel status + last handshake"
echo "    curl https://ifconfig.me         # should return the VPS public IP"
echo "    ip route                         # default via $WG_IFACE"
echo "    resolvectl dns                   # DNS should be 1.1.1.1 / 9.9.9.9 via wg0"
echo ""
echo "  If the VPN ever drops, the Pi has NO internet. That's the kill switch"
echo "  doing its job — there are no plaintext leaks."
echo ""
echo "  Reboot recommended: sudo reboot"
echo ""
